### ISSUE TITLE
Must jQuery still be a dependency ?

### ISSUE THREAD

**Issue by shinze** [alfajango/jquery-dynatable#245]

**Comment by JangoSteve** [comment]
jQuery is used mostly for compatibility reasons. I'd love to remove jQuery dependencies (and in fact, I had been slowly removing them with focused refactorings for a while), especially since a lot of what jQuery was used for could be pretty easily done with functionality now available in ES6. Definitely on the todo list.

**Comment by shinze** [comment]
Thank you !
